### ISSUE TITLE
Intellisense broken in cshtml

### ISSUE THREAD

**Issue by carjuzaa** [RehanSaeed/ASP.NET-MVC-Boilerplate#1]
When starting a project from scratch with the latest release, the intellisense is broken on the cshtml pages. Tried looking around the web.config files per some stackoverflow URLs like so:
http://stackoverflow.com/questions/22832435/mvc-razor-view-intellisense-broken-in-vs-2013

And also checking other places to find the culprit in the solution ...
http://thetoeb.de/2014/01/05/enabling-mvc5-intellisense-in-a-classlibrary-project/

... but no luck thus far. Any idea what could be causing this? I'm running this on VS2013 Ultimate. Thought it might be a bit of mix up on dependencies between some of the DLLs and MVC5.

![intellisense](https://cloud.githubusercontent.com/assets/10133544/6188839/1d43bb08-b374-11e4-9a39-eea7cd3a345c.PNG)

Best Regards!

**Comment by carjuzaa** [comment]
From doing a bit more troubleshooting I was able to fix the issue in the MvcBoilerplate by first commenting out the assembly redirects in the root web.config:

      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Owin" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="0.0.0.0-3.0.0.0" newVersion="3.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Web.Optimization" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="1.0.0.0-1.1.0.0" newVersion="1.1.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Web.Helpers" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="1.0.0.0-3.0.0.0" newVersion="3.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Web.WebPages" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="1.0.0.0-3.0.0.0" newVersion="3.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Autofac.Integration.Owin" publicKeyToken="17863af14b0044da" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.1.0.0" newVersion="3.1.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Web.Cors" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.2.3.0" newVersion="5.2.3.0" />
      </dependentAssembly>

Updating the mvc version in the view web.config:

<host factoryType="System.Web.Mvc.MvcWebRazorHostFactory, System.Web.Mvc, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31BF3856AD364E35" />

And by grabbing the git repo of elmah.mvc and upgrading the mvc version in that one to 5.2.3 thus replacing for quick testing the generated dll to the elmah.mvc packages folder so it uses that when rebuilding the project.

![intellisense](https://cloud.githubusercontent.com/assets/10133544/6189961/6f79d8d6-b37d-11e4-8ebb-2337540b6594.PNG)

**Comment by RehanSaeed** [comment]
Hi carjuzaa,

You are a star, thanks for the fix. Updating the MVC version in the Views Web.config seems to be sufficient to fix the problem. I've made the update and done a release of the project to the Visual Studio Gallery.

Rehan
