### ISSUE TITLE
Comment in generated FilterConfig.cs references RedirectToHttpsAttribute

### ISSUE THREAD

**Issue by dls314159** [RehanSaeed/ASP.NET-MVC-Boilerplate#10]
ASP.NET-MVC-Boilerplate/Source/MvcBoilerplateTemplate/App_Start/FilterConfig.cs in AddSecurityFilters references a RedirectToHttpsAttribute class on line 41.

If I uncomment this line, the RedirectToHttpsAttribute isn't found.

What am I missing?

**Comment by RehanSaeed** [comment]
Thanks for raising this. The RedirectToHttpsAttribute class is under the Framework folder and is not being picked up by the project for some reason. You can remove and re-add the file to the project to fix the problem.

I have now fixed this issue and will publish a update to the project template this afternoon. Thank You!

**Comment by mdocter** [comment]
The 'Build Action' property of the 'RedirectToHttpsAttribute.cs' file was set to 'Content' instead of 'Compile'.

**Comment by RehanSaeed** [comment]
Thanks good spot, I have now fixed this.
