### ISSUE TITLE
cshtml minifier tries to generate multiple min files. 

### ISSUE THREAD

**Issue by parmarnishant** [RehanSaeed/ASP.NET-MVC-Boilerplate#103]
![cshtmlminifier](https://cloud.githubusercontent.com/assets/3091518/16037139/d5225804-323c-11e6-9040-f42b61371310.PNG)

**Comment by RehanSaeed** [comment]
Yes, I think this may have been broken in the RC2 upgrade. I'll take a look at it.

**Comment by RehanSaeed** [comment]
Fixed in the next release.
