### ISSUE TITLE
Cdnizer

### ISSUE THREAD

**Issue by BitFlipp3r** [RehanSaeed/ASP.NET-MVC-Boilerplate#111]
Hi,

thanks for your great work @RehanSaeed !
Did you already consider using [gulp-cdnizer](https://www.npmjs.com/package/gulp-cdnizer) to get the package version for the cdn urls directly from bower.json?

Greetings
Michael

**Comment by RehanSaeed** [comment]
That looks like a pretty cool project. However here are some questions I have which need a little more digging:

1. Does it work with .cshtml files? It looks like it handles html and css. It probably does a find and replace on the URL but not sure.
2. If it does a find and replace, we would need to have two copies of our views. The original and the one output by the Gulp task. I've done that with my .cshtml minification feature which outputs .min.cshtml files but not sure how I feel about it.
3. Large public CDN's are usually pretty slow to update to the latest version of resources. How does this package handle the fact that a CDN resource for a particular version might not exist.

**Comment by BitFlipp3r** [comment]
Hi, I have to admit that I have not used the lib yet. Just thought it would be nice to have my cdn paths automatically updated.

1. I don't think the file extension matters. The lib says "will replace local file references in HTML and other files ".
2. Yeah I guess we would need two copies. I personally don't mind the min.cshtml. (great feature btw) Would it be possible to minify after cdnizing and combine the output? 
3. Vendor specific CDNs (like jquery, bootstrap, etc.) usually have the latest version right away. You can still hardcode your cdn path without a dynamic version via "cdn" property for slow CDNs.

Greetings

**Comment by RehanSaeed** [comment]
The minification feature is Beta for a reason. It's not doing all the minification that could be done, it only removes **most** white space, doesn't do all the other minification stuff and it's not properly tested. I built it mostly to show the devs at Microsoft what could be done. I don't think my Gulp task is the path the Microsoft devs will take because they are moving away from using Gulp and want to be front-end build tool agnostic.

Without cshtml minification, creating new cshtml files just for CDN URL replacement seems overkill but I like the idea of piping cshtml files through Gulp in general. I think there are a few tricks we are missing in this space.

Maybe this would be better served with a TagHelper!!!

**Comment by BitFlipp3r** [comment]
Yeah you're probably right. I'm excited on what's to come!
Although I don't think that everybody is going to ditch gulp. I was pleased at first that MS devs dropped gulp again, but then I realized that I actually miss it. At some point you just can't cut it with MS tools/VS extensions, whereas gulp has a plugin for basically everything. Web Compiler is doing a great job with minification and bundling but I personally miss a way to [purify css](https://github.com/purifycss/gulp-purifycss) right now. That's why I like your template better than the default mvc core template. And I don't like mixing to many tools so I'll propbalby stick with gulp.
Well... Thanks for your feedback!
Greetings
Michael

**Comment by RehanSaeed** [comment]
Totally agree with you on both points.

The default template is ok for a newbie developer but at some point you need to use Gulp/Brocolli/Etc to do things properly but it takes so much time to setup. The idea behind this template is to get rid of that setup time.

I've tried to reduce the dependencies to an absolute minimum but it's so ridiculously hard to do with NPM. We actually have a 1 star review complaining that we download "the whole of NPM". The thing is I'm not sure what else I'd cut.

**Comment by RehanSaeed** [comment]
I will think about a TagHelper that reads the bower.json or package.json file and uses the version number to do a replace. So something like this:

```
<environment name="Development">
  <script src="js/jquery.js"></script>
</environment>
<environment name="Staging,Production">
  <script asp-cdn-template="https://google-cdn.com/{version}/jquery.js"
              asp-cdn-package-bower="jquery"></script>
</environment>
```

**Comment by BitFlipp3r** [comment]
Sounds great!
I don't think you should cut anything, that's not the point of your project. Just make sure that it stays pluggable to some degree (as it is), so you don't loose the saved time on removing unwanted features.

**Comment by RehanSaeed** [comment]
There is a [TODO list](https://github.com/RehanSaeed/ASP.NET-MVC-Boilerplate/blob/master/TODO.md) of existing stuff I want to turn into an optional feature e.g. Google Page Speed, SCSS etc. but I have not time.

**Comment by RehanSaeed** [comment]
This has been added to the TODO list, you'll see this feature eventually. Closing for now.
