### ISSUE TITLE
MVC unobtrusive ajax will not work - UnsafeInline

### ISSUE THREAD

**Issue by fruitbatinshades** [RehanSaeed/ASP.NET-MVC-Boilerplate#113]
I'm struggling to get mvc unobtrusive ajax to work with boilerplate. My config is below can you suggest how to handle this?
------------------------------------------------------------------------------------------------------------
Error: call to Function() blocked by CSP
	
...=="function")return a;b.push(d);return Function.constructor.apply(null,b)}functi...
	
jquery.....min.js (line 19, col 234)
Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src http://localhost:62501 'unsafe-inline' localhost:").

call to eval() or related function blocked by CSP
------------------------------------------------------------------------------------------------------------

        private static void AddContentSecurityPolicyFilters(GlobalFilterCollection filters)
        {
            filters.Add(new CspAttribute());
            filters.Add(new CspReportUriAttribute() { EnableBuiltinHandler = true });

            filters.Add(
                new CspDefaultSrcAttribute()
                {
                    Self = true
                });

            filters.Add(
                new CspBaseUriAttribute()
                {
                    Self = false
                });
            filters.Add(
                new CspChildSrcAttribute()
                {
                    Self = false
                });
            filters.Add(
                new CspConnectSrcAttribute()
                {
        #if DEBUG
                    CustomSources = string.Join(" ", "localhost:*", "ws://localhost:*"),
        #else

        #endif

                    Self = true
                });
            filters.Add(
                new CspFontSrcAttribute()
                {
                    Self = true
                });
            filters.Add(
                new CspFormActionAttribute()
                {
                    Self = true
                });
            filters.Add(
                new CspFrameSrcAttribute()
                {
                    Self = false
                });
            filters.Add(
                new CspFrameAncestorsAttribute()
                {
                    Self = false
                });
            filters.Add(
                new CspImgSrcAttribute()
                {
                    Self = true
                });
            filters.Add(
                new CspScriptSrcAttribute()
                {
                    CustomSources = "localhost:",
                    Self = true,
                    UnsafeInline = true
                });
            filters.Add(
                new CspMediaSrcAttribute()
                {
                    Self = false
                });
            filters.Add(
                new CspObjectSrcAttribute()
                {
                    Self = true
                });
            filters.Add(
                new CspStyleSrcAttribute()
                {
                    Self = true,
                    UnsafeInline = true
                });
        }

**Comment by RehanSaeed** [comment]
Based on "call to eval() or related function blocked by CSP" you or a library you are using (unobtrusive ajax) are trying to use the `eval()` JavaScript function which is not allowed by default. The `CspScriptSrcAttribute` has an UnsafeEval property which you would need to set to true but bear in mind that this puts a security hole in your CSP policy (unfortunately not every library out there plays nicely with CSP yet so this is sometimes required).

**Comment by fruitbatinshades** [comment]
Thanks RehanSaeed, I'll look into other options as well, I didn't want to turn that on.

**Comment by RehanSaeed** [comment]
Feel free to reopen if you need more help.
