### ISSUE TITLE
[Question] - Upgrading

### ISSUE THREAD

**Issue by dotnetshadow** [RehanSaeed/ASP.NET-MVC-Boilerplate#114]
Hi there,

Firstly I wanted to say you have done an amazing job with this template, it has so many great features.

I love all the updates that you keep doing, I'm just a little concerned about how to keep upgrading existing projects. 

How would you suggest someone goes about minimising the impact of upgrading various files in the project? Say I'm version 4.0 but now the project is 4.2.2 there are many changes do they have to all be manually added? Is there an upgrade guide of some sort?

**Comment by RehanSaeed** [comment]
This is a good question. I talk about it towards the end of the ReadMe.html file.

Some of the upgrades would come from just upgrading the Boilerplate NuGet packages. Others would mean making code changes to the template files and there is no way for me to make these changes for you. You can review the Release Notes to see what has changed in this case.

**Comment by jofran73** [comment]
Hi,
I just found out about boilerplate and already learned a lot from it.
The upgrading question is one of the first things that came into my mind. Wouldn't it be possible to split boilerplate into two projects?
A - The template with all the setup code and configuration you wouldn't want to auto-update anyway
B - A class library with all the helpers, filters, middleware, etc. that is distributed via npm

Thank you very much for sharing the awesome work you are doing.

**Comment by RehanSaeed** [comment]
I already ship as much shared code as possible already in Boilerplate.AspNetCore.* NuGet packages. All helpers, filters and middleware is contained within.

**Comment by jofran73** [comment]
Of course. I've been so heads deep into all the new stuff with .net core that I didn't check the obvious NuGet. Perfect!

Thanks and sorry for bothering you.

**Comment by RehanSaeed** [comment]
@jofran73 No worries :)
