### ISSUE TITLE
manifest.json has a trailing slash because it isn't removed in _Layout.cshtml

### ISSUE THREAD

**Issue by Matthew-Bonner** [RehanSaeed/ASP.NET-MVC-Boilerplate#117]
When creating a project, in ~/Views/Shared/_Layout.cshtml on line 80 the following code:
`<link rel="manifest" href="@Url.RouteUrl(HomeControllerRoute.GetManifestJson)">`

Should be changed to:
`<link rel="manifest" href="@Url.RouteUrl(HomeControllerRoute.GetManifestJson).TrimEnd('/')">`

**Comment by Matthew-Bonner** [comment]
If you want me to create a pull request to fix this bug please let me know.

**Comment by RehanSaeed** [comment]
Would appreciate a PR.
