### ISSUE TITLE
Provide a way to donate to help fund this project.

### ISSUE THREAD

**Issue by Matthew-Bonner** [RehanSaeed/ASP.NET-MVC-Boilerplate#120]
Most open source projects have a way to donate money to keep them active and having the ability to donate to the author is also a nice way to say thanks for the hard work. I think this project will benefit from having a way to donate financially and I also think the project is big enough to warrant accepting donations.

**Comment by RehanSaeed** [comment]
Thanks for thinking this project is big enough, really appreciate that. I started this project as a way to learn and contribute to the community. I have limited time but do try to release new features every week (Delayed this week, trying to add a feature to select a web server Kestrel/IIS/Nginx and am learning Nginx in-depth to do it). Donating would not speed up my development but I suppose would let people do the equivelant of buying a virtual coffee.

**Comment by RehanSaeed** [comment]
Added to the [TODO](https://github.com/RehanSaeed/ASP.NET-MVC-Boilerplate/blob/master/TODO.md).
