### ISSUE TITLE
Set RouteExistingFiles to true

### ISSUE THREAD

**Issue by Matthew-Bonner** [RehanSaeed/ASP.NET-MVC-Boilerplate#123]
For discussion:
Set RouteExistingFiles to true to increase performance by removing the need to check the file system to see if an existing path exists, and to allow people to create pages under the path "/services" as most websites which provide a service will use this path.

If you are happy to go ahead with this change I'll create a PR. Thanks.

**Comment by Matthew-Bonner** [comment]
See the paragraph below:
http://www.hanselman.com/blog/PlugInHybridsASPNETWebFormsAndASPMVCAndASPNETDynamicDataSideBySide.aspx#highlighter_148896

**Comment by RehanSaeed** [comment]
Interesting read @Matthew-Bonner. It also says:

> A best (and example of attention to detail) practice would be to put in an IgnoreRoute call for those pages, directories, and/or HttpHanders.

`IgnoreRoute` does not exist in MVC 6 yet for some reason and I think (not sure) I've configured it correctly for MVC 5 but please go ahead and submit a PR if I'm wrong. Much appreciated!

**Comment by RehanSaeed** [comment]
Feel free to re-open this if you find something.
