### ISSUE TITLE
Bower vs NPM

### ISSUE THREAD

**Issue by Ketrex** [RehanSaeed/ASP.NET-MVC-Boilerplate#126]
This is just a question, but has there been any consideration given to abandoning reliance on Bower and just using NPM? It seems a lot of frameworks are not setting up Bower feeds (Angular 2 comes to mind) anymore. Anyway, just a thought.

**Comment by RehanSaeed** [comment]
Yes, yes and yes. I'm totally starting to think that will be the new default. Bower gives us nothing but extra 'stuff' to deal with. Added to the [TODO](https://github.com/RehanSaeed/ASP.NET-MVC-Boilerplate/blob/master/TODO.md) page.
