### ISSUE TITLE
Glimpse 404 on install

### ISSUE THREAD

**Issue by avisser** [RehanSaeed/ASP.NET-MVC-Boilerplate#13]
I want to try this project out, but on a clean install, VS2013 Update 4, I get a 404 when visiting ~/glimpse.

I Googled around for a while, but everything seems correct.

I can view the Trace and Elmah screens, just not Glimpse.

**Comment by RehanSaeed** [comment]
It seems the custom route for Glimpse has stopped working when we add a default MapRoute entry in to make Elmah work. We can go back to the glimpse.axd route to fix this. I have updated the repository, I will submit an update soon. In Web.config change:

path="glimpse" to path="glimpse.axd"
endpointBaseUri="~/glimpse" to endpointBaseUri="~/glimpse.axd"

In _Layout.cshtml change
/glimpse to /glimpse.axd

**Comment by avisser** [comment]
Thanks for the quick turnaround.

Unrelated, do you have a preferred Auth provider to integrate into your Boilerplate? Either MSFT Identity or other?

**Comment by RehanSaeed** [comment]
No problem.

I get asked this a lot, I will make a note to add an Authentication section to the ReadMe.html file, outlining your options. Basically, I reccomend using Microsfts Identity NuGet package, I'm not sure what other good alternative there is. I definately do not reccomend rolling your own. Unless you are a security guru, you will make mistakes. Authentication, login, logoff, remember me, forgot my password etc. is a massive headache.

**Comment by avisser** [comment]
I just updated the Visual Studio Extensions, created a new project, and the issue is still there.

**Comment by RehanSaeed** [comment]
I just tested it, seems fine. The path is now /glimpse.axd not /glimpse.

**Comment by avisser** [comment]
I got it to work. However I have to navigate to ~/glimpse.axd/. I still get
a 404 if I leave off the trailing slash. I've updated my _layout.cshtml.

Thanks,
Andy

**Comment by RehanSaeed** [comment]
Hmmm...let me check that. Does the link in the debug menu of the site work for you?

Rehan Saeed

-----Original Message-----

**Comment by avisser** [comment]
No, the debug link isn't working, only manually entering the trailing slash.

-Andy
