### ISSUE TITLE
Treat Warnings as Errors by default

### ISSUE THREAD

**Issue by omidkrad** [RehanSaeed/ASP.NET-MVC-Boilerplate#15]
In project properties set **Build** -> **Treat warnings as errors** to **All**.

**Comment by RehanSaeed** [comment]
I think this is personal preference. Some people would not want this and it's easy for you to click on the show warnings toggle button to see those too.

**Comment by omidkrad** [comment]
This setting is usually a requirement in large teams. I think at least the boilerplate should compile with no warnings on first run and maybe add it to the boilerplate's checklist.
