### ISSUE TITLE
Is't support ASP NET Identity?

### ISSUE THREAD

**Issue by biapar** [RehanSaeed/ASP.NET-MVC-Boilerplate#16]
Is't support ASP NET Identity? If yes, how to use with your solution?

**Comment by RehanSaeed** [comment]
Many people have asked me this question so I will refer them all here with a more generic answer.

## Introduction

When you create a new default Web Project, you are shown a dialogue which allows you to select the type of authentication you want to use in your site. There are four options available but unfortunately Microsoft does not allow third party developers to access this dialogue. I have submitted my feedback to Microsoft developers and am waiting for a response.

## Windows Authentication

This is good for internal intranet websites. This is pretty easy to set up by simply turning on Windows authentication and turning off Anonymous authentication on your site. You can view a tutorial [here](http://www.asp.net/mvc/overview/older-versions-1/security/authenticating-users-with-windows-authentication-cs)

## Individual Authentication using ASP.NET Identity

This uses the familiar username and password, using login, register, forgot your password, account and change password pages on your site, account information can be stored on your own site or using popular account holders like Microsoft Account, Google Plus, Facebook, Twitter etc.

Setting up individual account authentication is best done using the [ASP.NET Identity](http://www.asp.net/identity) NuGet package. **Do not** set up your own custom account management facilities unless you are a security genius and really know what you are doing. Even large companies get this massively wrong. Many people have asked me how to do this, my answer is to install the NuGet package and follow the instructions in the above link.

**Comment by biapar** [comment]
Ok. So Do I only use nuget and install asp.net identity and all works? 

Saluti
ing. Biagio Paruolo
Inviato da iPhone6

**Comment by RehanSaeed** [comment]
Yes but ASP.NET Identity is a really complicated piece of code. I would read all the documentation in the link I posted and watch the video too.

**Comment by biapar** [comment]
So, what do you suggest for membership?

**Comment by RehanSaeed** [comment]
Use ASP.NET Identity.

**Comment by biapar** [comment]
Ok. How to use it into your template? I've installed by nuget but now must be include/copy/build controllers/views/etc into your template like when you activate identity from a VS2013 MVC project.

**Comment by RehanSaeed** [comment]
Right now, I have no guidance on this. I'm focusing on MVC 6 and will add ASP.NET Identity later or Microsoft will allow its integration using their special dialogue which they have locked out third party developers from.

**Comment by biapar** [comment]
I think that you need to start from a VS2013 solution mvc/mvc webapi with single authorization. So after you need to put in your packages.

**Comment by biapar** [comment]
I already have ASP.NET Identity with Unity IOC.
