### ISSUE TITLE
please consider a more liberal license

### ISSUE THREAD

**Issue by joeaudette** [RehanSaeed/ASP.NET-MVC-Boilerplate#24]
currently this project is licensed as GPL which is kind of a poison pill because of its viral clause which means anyone who uses this project must also make their own project code licensed under GPL.
I cannot use this project for anything with the current license, not even in my own open source projects which are not GPL. 

Please consider something more liberal like MIT or apache 2 license. Note that Microsoft uses apache 2 for the open source asp.net 5 mvc 6 framework, it would be more consistent if this project used the same.

**Comment by RehanSaeed** [comment]
@joeaudette Thanks Joe. I must admit I hadn't given this much thought. I've been looking at [choosealicense.com](http://choosealicense.com/) and I think MIT would work. I've now made the switch to MIT.
