### ISSUE TITLE
OpenGraphMedia mediaUrl HTTPS

### ISSUE THREAD

**Issue by AndyDalton** [RehanSaeed/ASP.NET-MVC-Boilerplate#26]
When using a HTTPS URL with a class derived from OpenGraphMedia class it sets the HTTP URL as well but leaves the port number in the URL. This outputs an invalid URL in the metadata (i.e.: http://www.example:443.com).

In the constructor of the OpenGraphMedia class it uses a UriBuilder to change schemes if the mediaUrl is HTTPS.  If the port value was set to -1 it would use the default for the scheme and should generate the correct HTTP counterpart (i.e.: http://www.example.com).  I think this should be sufficient.  Many thanks in advance.

**Comment by RehanSaeed** [comment]
Thanks @AndyDalton. Yes that is a bug. I'll get that fixed an an update to the NuGet package.

```
this.mediaUrl = new UriBuilder(mediaUrl)
{
    Port = -1,
    Scheme = Uri.UriSchemeHttp
}.ToString();
```

**Comment by AndyDalton** [comment]
Awesome, I've upgraded the NuGet package and it is resolved.  Many thanks.

**Comment by RehanSaeed** [comment]
@AndyDalton I fixed several other issues with the OpenGraph HTML helper and also am working on converting the MVC 6 version to be used as a TagHelper, as well as a HTML helper. Go ahead and install the update to the NuGet package. You can view the change history for the changes made.

I still haven't updated the project template to the new version of the NuGet packages. I've got a bunch of changes stacked up and ready for release.

**Comment by AndyDalton** [comment]
That's excellent, many thanks for the update.
