### ISSUE TITLE
Debug menu should not show in the Release build

### ISSUE THREAD

**Issue by omidkrad** [RehanSaeed/ASP.NET-MVC-Boilerplate#29]
When you run the website as **Release**, the *Debug* menu with *Runtime Information* should not render.

**Comment by RehanSaeed** [comment]
This was true for MVC 5 but MVC 6 has changed a lot. You have to now use the environment variable to control the Development, Staging and Production environments. The Debug and Release config now just controls the building of DLL's and precompiling views.

**Comment by omidkrad** [comment]
Good to know. That makes sense for dnx/multi-platform. Thanks.
