### ISSUE TITLE
MVC6 Boilerplate does not work if there is no specific package source in NuGet

### ISSUE THREAD

**Issue by wzuo** [RehanSaeed/ASP.NET-MVC-Boilerplate#32]
Hi,
there are missing packages by default in MVC6 Boilerplate if one does not have added specific package source in NuGet.
Packages which can't be downloaded and installed:
`"Newtonsoft.Json": "7.0.1"`
`"Boilerplate.Web.Mvc6": "1.2.0"`

Solution is to add ASP.NET master package source from myget in `Tools -> Options -> NuGet Package Manager -> Package Sources`:
Name: `ASP.NET master`
Source: `https://www.myget.org/F/aspnetmaster/api/v2`

Readme is missing about that topic, so please add it :)

**Comment by RehanSaeed** [comment]
Excellent, thanks @wzuo. I remember doing that but it would be good to add it to the pre-requisites.
