### ISSUE TITLE
Lifetime of CacheService

### ISSUE THREAD

**Issue by davidsekar** [RehanSaeed/ASP.NET-MVC-Boilerplate#39]
The CacheService is added to AutoFac with the Lifetime scope as InstancePerRequest. Should the DI create new MemoryCache service every request & dispose the cached objects ?

**Comment by RehanSaeed** [comment]
The CacheService is a wrapper around the static:

```
this.memoryCache = MemoryCache.Default;
```

So in this case it doesn't really matter too much. However, I'll change this to a singleton in the next update.

**Comment by RehanSaeed** [comment]
Done
