### ISSUE TITLE
v2.8 issues

### ISSUE THREAD

**Issue by dotnetshadow** [RehanSaeed/ASP.NET-MVC-Boilerplate#43]
Hi there,

I found a couple of issues after building v2.8 (commit: da1254f6055d2df01b3382a4be6de92219e8423f) , I couldn't find the compiled vsix on visual studio gallery. 

I created a new project using .net 4.5.2, choosing default options:

**1) _ViewImports.cshtml**
Referencing ***Microsoft.Framework.OptionsModel*** but should be referencing ***Microsoft.Extensions.OptionsModel***

**2) gulpfile.js**
autoprefixer = require("gulp-autoprefixer") missing comma at the end  of line

There is an warning using "strict" in gulpfile.js for ***require***, it states that "Using a variable (property or object) without declaring it is not allowed in  in 'strict mode', You may need to declare var require;

**3) JSHint Errors)**
If you choose the ***JsHint*** option then there is an error with gulpfile, if you don't choose JsHint as an option everything works correctly
```
Failed to run "D:\Programming\Projects\AspNetMvcBoilerPlate\WebApplication4\WebApplication4
\Gulpfile.js"...
cmd.exe /c gulp --tasks-simple
module.js:338
    throw err;
          ^
Error: Cannot find module 'jshint/src/cli'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (D:\Programming\Projects\AspNetMvcBoilerPlate\WebApplication4\WebApplication4\node_modules\gulp-jshint\src\extract.js:1:79)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

Failed to run "D:\Programming\Projects\AspNetMvcBoilerPlate\WebApplication4\WebApplication4\Gulpfile.js"...
cmd.exe /c gulp --tasks-simple
module.js:338
    throw err;
          ^
Error: Cannot find module 'jshint/src/cli'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (D:\Programming\Projects\AspNetMvcBoilerPlate\WebApplication4\WebApplication4\node_modules\gulp-jshint\src\extract.js:1:79)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

**Comment by RehanSaeed** [comment]
The latest commit is not released due to a problem with RC1. Please see the latest closed pull request for more info.
I'll add your fixes to my list.

**Comment by dotnetshadow** [comment]
Excellent thank you

**Comment by RehanSaeed** [comment]
First two errors fixed. Thanks.

**Comment by RehanSaeed** [comment]
Apparently there will be a ASP.NET 5 RC1 Update 1 release soon. Hopefully it will fix the issues so I can release.

**Comment by dotnetshadow** [comment]
Oh great, thanks for the update. Is there any page where they have announced upcoming ASP.NET 5 RC1 Update 1?

**Comment by RehanSaeed** [comment]
Only discussed in the ASP.Net community standup meetings.

**Comment by dotnetshadow** [comment]
Thanks once again I will definitely check out those videos

**Comment by dotnetshadow** [comment]
I got another issue which I'm not sure if you have come across, I've posted on StackOverflow because I'm unsure if it's an issue with Firefox / IIS or this project:
http://stackoverflow.com/questions/34034068/firefox-https-404-errors

Basically I'm using this method to run the project
https://github.com/tuespetre/dnx-watch-iis

**Comment by RehanSaeed** [comment]
Not sure, I haven't used dnx watch yet. Does Browser Link not work for you? It achieves the same objective I think. Not sure what the difference is yet, need to do some reading.

FYI, I'm keeping this open until I fix the JSHint errors.

**Comment by dotnetshadow** [comment]
Thanks for keeping the issue open until JSHint is fixed

The firefox is as follows:
127.0.0.1 local-foo.com
In IIS I set a binding for HTTP and HTTPS for local-foo.com and create a self signed certificate.

Using your template I get these aborted request errors, but if I use the ASP.NET template instead then I do not get these errors. I know your template makes use of security features I'm just wondering something must be making Firefox act differently.

I have tried different computers but the issue only exists with Firefox in HTTPS mode using IIS.
I'm just worried that in published mode that Firefox might have issues with HTTPS with this template?

**Comment by RehanSaeed** [comment]
Well, NWebSec does not exist yet for ASP.NET 5, so no security features yet. Let me know if you figure anything out on your side.

**Comment by dotnetshadow** [comment]
Yes I definitely will, just debugging and see what's different between the two solutions.

**Comment by dotnetshadow** [comment]
Looks like there is nuget update for dnx RC1 update1
https://www.nuget.org/packages/dnx-clr-win-x86/1.0.0-rc1-update1

**Comment by RehanSaeed** [comment]
Cool, nice spot.

**Comment by dotnetshadow** [comment]
In case you didn't know the installer is now available for RC 1 update 1 @ http://get.asp.net/

**Comment by RehanSaeed** [comment]
All updated. Just doing some final testing.
