### ISSUE TITLE
v2.8 css / js / gulpfile not outputting correctly

### ISSUE THREAD

**Issue by dotnetshadow** [RehanSaeed/ASP.NET-MVC-Boilerplate#45]
Hi there,

I noticed you removed "webroot": "wwwroot" in project.json. But your gulpfile refrences project.webroot  so when building the gulp file nothing gets outputted

```
 // Destination Directory Paths
    wwwroot: "./" + project.webroot + "/",
    css: "./" + project.webroot + "/css/",
    fonts: "./" + project.webroot + "/fonts/",
    img: "./" + project.webroot + "/img/",
    js: "./" + project.webroot + "/js/"
```

Maybe you need to introduce a hosting.json file:

    Hosting:DetailedErrors - Show detailed errors for startup failures
    server or Hosting:Server - Specify which servers
    app or Hosting:App - Application where the startup is
    ASPNET_ENV or Hosting:Environment - The environment to run as (Development, Production etc)
    webroot - Webserver root, used by iis and static file servers

**Comment by RehanSaeed** [comment]
Yes, my mistake. The project.json no longer has this setting so it needs to be moved to hosting.json. Released 2.8.1.
