### ISSUE TITLE
BrowserConfig.xml still has a trailing slash

### ISSUE THREAD

**Issue by dotnetshadow** [RehanSaeed/ASP.NET-MVC-Boilerplate#47]
Hi 

I noticed that certain html resources have a trailing slash, even though [NoTrailingSlash] has been specified.

```
<meta name="msapplication-config" content="@Url.RouteUrl(HomeControllerRoute.GetBrowserConfigXml)">

produces

<meta name="msapplication-config" content="/browserconfig.xml/">
```

I noticed the manifest.json also has the same problem

**Comment by RehanSaeed** [comment]
The `NoTrailingSlashAttribute` is used to tell the `RedirectToCanonicalUrlAttribute` filter that the URL does not need a trailing slash. It does not help with the `IUrlHelper` although it would be nice if it did. I'm not sure there is an extensibility point for me to add this feature, so for now I use `.TrimEnd('/')` when using the `IUrlHelper` with these particular URL's.

Perhaps you could raise an issue on the ASP.NET MVC GitHub project, explaining the reason why some URL's need trailing slashes removed and also linking to this issue. If not, I'll raise one when I get a chance.

I've fixed the above issue and will do a patch release. Let me know if you find any others.

**Comment by dotnetshadow** [comment]
Oh thank you for clearing that up it makes sense after you explained. I'll see if I can raise an issue but perhaps they will listen to you more hehehe

**Comment by RehanSaeed** [comment]
Fixed. I have raised [this](https://github.com/aspnet/Mvc/issues/3740) issue on the ASP.NET MVC GitHub page.

**Comment by dotnetshadow** [comment]
Excellent good work, hopefully they can have a fix for this well done
