### ISSUE TITLE
Add support for less

### ISSUE THREAD

**Issue by ChrisOMetz** [RehanSaeed/ASP.NET-MVC-Boilerplate#51]
Instead of using sass I prefer less for styling my CSS files.
Therefore I would love to see support - maybe as a select option during initialization - for this kind of stylesheet writing.

**Comment by RehanSaeed** [comment]
Yes, that is a great idea. Right now, I don't have time to add this feature but it is something that I have wanted to do. I'll leave this issue open for now.

I made a conscious decision to switch from LESS to SASS when I created the MVC 6 project template. This is what the majority of the CSS developers are using, while it seems that LESS is used by the majority of Microsoft focused developers. However, I think LESS is still a nice language. I have also thought about adding a third option which movers and shakers in the CSS world have been advocating.

**Comment by RehanSaeed** [comment]
I still think this is worth doing but this is worth reading http://www.developerdrive.com/2015/12/what-you-need-to-know-about-bootstrap-4/

**Comment by ChrisOMetz** [comment]
thanks for this information. No, I haven't heard about that and wish to read this a week ago :-)
On one side I really appreciate a "unification" of development practices although I do not like the direction in which this unification points to.
I have made for to much investments in existing customer projects just to make such a switch very easy and I don't think that I would like to switch even in running projects simply because my customers will not pay for these things.
Furthermore I don't like the new overall openness of these original Microsoft standards at all. I have never ever faced a customer who has to support one projects on different environments. I also don't get into the versioning hell of linux where there are hundreds of different packaging systems with the hell of dependencies for each individual micro function. Should I use npm, bower, pip, yum or nuget, grunt or gulp, less or sess, bootstrap or yup, angular or knockout, ... I really don't want to get to know all of these, I want to re-focus on develop my projects.
But sorry. Before I rage out to much. This is a completely different story.

An offer for a Less support is there. Currently bootstrap-less only support version 3.3.4 (one more of this versioning hell out there...)

Use it as you think it suits best for this project.

**Comment by RehanSaeed** [comment]
I feel the same way. Finding out what to use is half the effort sometimes, the web in particular has too much choice. Eventually, I'd like to upgrade the project to use Bootstrap 4.0.

I think we'll watch what the Bootstrap team does with 4.0. If they drop Less support entirely then there is no point adding Less here.

Have you heard of PostCSS? The Bootstrap team almost moved to this and it seems to be gaining traction in the community and it will probably be the future although it is not certain at this stage.

**Comment by ChrisOMetz** [comment]
sigh. Yet another thing from which I learn that I have to learn to do my job. I wonder how I ever could complete any project without.
But this reminds me of the ongoing discussion about the data access layer. At the start there was an ADODB.Object with SQL statements, than came DataTable / DataReader, next to LinqToSQL and the first EnitityFramwork. Between was the ORM and Micro-ORMs and now EF7 only. 
But to be honest. Instead of solving a problem and making things easier I just have to learn a new DAL nearly every year. Furthermore at the end there is still just a simple SELECT statement after all.

And now these things happen again, but just with the topic of "making a headline appear bigger than normal text". Yes, it is fun to learn about new thing like an parser that translates something into something, hands it over to another thing to .. what? to just generate my additional custom stylesheet definitions.

Am I wrong or is there something missing? My main point is to get this web site out to my customer as fast and robust as possible and be able to maintain it even after some years with the next versions of Visual Studio and the wave of newest and hottest thing in the world. My question than is, will npm and all my required packages still available, when I try to open and recreate my project in 5 years?

**Comment by RehanSaeed** [comment]
If you want simple database access, take a look at Dapper which is created and used by StackOverflow. It's pretty good and very fast. EF is the other main alternative these days.

Yes I have had that thought too. The version numbers on NPM packages change ridiculously fast (I update them regularly). The packages will still be there ten years from now (Unless the GitHub repositories go down) but everything will be out of date and ancient.

**Comment by ChrisOMetz** [comment]
Dapper is too big in my opinion :-) I prefer Massiv which is just 2 or 3 class which I simply add without any packet manager to my code and go for SQL statements myself.
BTW: Are we still on topic? :-)

**Comment by RehanSaeed** [comment]
Closing for now. Wil re-open when we find out more about Bootstrap 4.
