### ISSUE TITLE
Application Insights

### ISSUE THREAD

**Issue by dotnetshadow** [RehanSaeed/ASP.NET-MVC-Boilerplate#54]
Hi there,

I can log errors to the application insights, but I can't seem to get the exception message to display in azure. The following are 2 screenshots. The first being what asp.net mvc boilerplate shows in azure when an error occurs. The second screenshot shows the default asp.net template and what it produces. The exception I'm trying to produce is divide by zero in controller.

**ASP.NET MVC6 BoilerPlate Exception**
You can see that it's treating it as an error 500 response code 
![exceptions](https://cloud.githubusercontent.com/assets/296247/11977219/dcaea1e0-a9d4-11e5-8be5-52383a1ca7e7.PNG)

**DEFAULT ASP.NET MVC6 TEMPLATE Exception**
This is how the exception should really look notice no response code and you can see the exception message
![correct](https://cloud.githubusercontent.com/assets/296247/11977664/e5eff9b2-a9d8-11e5-80b4-77ae4638b373.PNG)

Also I noticed in the Microsoft template they use 
```
**_ViewImports.cshtml**
@inject Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration TelemetryConfiguration

**_Layout.cshtml**
@Html.ApplicationInsightsJavaScript(TelemetryConfiguration)
```

**Comment by dotnetshadow** [comment]
Actually I think I may of figured out the issue. When I flipped the ordering of the following I could see the exception. I noticed in Microsoft default template the order is as below

**Startup.cs**
```
// Track data about exceptions from the application. Should be configured after all error handling 
// middleware in the request pipeline.
application.UseApplicationInsightsExceptionTelemetry();

// Add MVC to the request pipeline.
application.UseMvc();
```

**Comment by RehanSaeed** [comment]
:+1:  I checked in a fix based on [this](https://github.com/search?q=UseApplicationInsightsExceptionTelemetry+UseIISPlatformHandler&type=Code&utf8=%E2%9C%93) search. Will be released in next patch update later today.
