### ISSUE TITLE
An unhandled exception of type 'System.AccessViolationException' occurred in Glimpse.Agent.AspNet.dll

### ISSUE THREAD

**Issue by renathy** [RehanSaeed/ASP.NET-MVC-Boilerplate#55]
"An unhandled exception of type 'System.AccessViolationException' occurred in Glimpse.Agent.AspNet.dll"
It goes to "Break mode". Afterwards web browser just shows IIS 10.0 detailed error: "HTTP Error 502.3 - Bad Gateway
The specified CGI application encountered an error and the server terminated the process."

I am getting this error when trying to run project in debug mode. If I run it without debugging, it opens.

P.S. I have additional question:
- After installing Boilerplate (for asp.net mv6) I am getting "Invalid expression term ')'	XXX.DNX 4.5.1, XXX.DNX Core 5.0	C:\_XXX\XXX\XXX\Startup.ContentSecurityPolicy.cs	118	Active
 filters.Add(
                new CspConnectSrcAttribute()
                {
                    // Allow AJAX and Web Sockets to the following sources.
                    CustomSources = string.Join(
                        " ",
                        // CustomSources = "*.example.com",     // Allow AJAX and Web Sockets to example.com.
                        ),
                    // Allow all AJAX and Web Sockets calls from the same domain.
                    Self = true
                });

I removed this filter, is it ok?

I am very new to asp.net 5 and mvc 6, as well as your template.

**Comment by RehanSaeed** [comment]
Have you installed the latest tools? Did you run `dnvm upgrade`? Are you trying to use full IIS (See [here](https://github.com/aspnet/Home/issues/1000)).

**Comment by RehanSaeed** [comment]
Did the answer in the other linked issue solve the problem for you?

**Comment by ayodahunsi** [comment]
Hi Rehan, 
I have a similar error to the one mentioned above after i created a fresh project using your template:
Error	CS1525	Invalid expression term ')'	WebApplication5.DNX 4.5.1, WebApplication5.DNX Core 5.0	c:\users\ayo\documents\visual studio 2015\Projects\WebApplication5\WebApplication5\Startup.ContentSecurityPolicy.cs	122	

This is the code on the line 122:
![image](https://cloud.githubusercontent.com/assets/9487333/12317635/3819ca06-ba50-11e5-9f69-d0f7685c4b02.png)

I already ran dnvm upgrade and it says it is already up to date.

**Comment by RehanSaeed** [comment]
Delete the extra comma to fix the issue. I've released a new version of the template to get this fixed in future.
