### ISSUE TITLE
VS community 2015 crash

### ISSUE THREAD

**Issue by pedrotainha** [RehanSaeed/ASP.NET-MVC-Boilerplate#56]
When i try to create a new project based on MVC6 template the VS crash, does someone know why this is happening. Thanks in advance.

**Comment by RehanSaeed** [comment]
Can you give any more info. What actually happens? Do you see any error messages? Did you check the event log?

**Comment by pedrotainha** [comment]
I tryed to reproduce now, but the VS just didn'd crash.  if happen again i
will try to log more information.

2016-01-06 8:41 GMT+00:00 Muhammad Rehan Saeed <notifications@github.com>:

> Can you give any more info. What actually happens? Do you see any error
> messages? Did you check the event log?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RehanSaeed/ASP.NET-MVC-Boilerplate/issues/56#issuecomment-169267575>
> .
>



-- 

Com os melhores cumprimentos,

Pedro Tainha
.: Marque a sua presença na Internet :.

www.pedrotainha.com
 facebook.com/pedrotainha.webdesign
http://pt.linkedin.com/in/pedrotainha

CONTACTOS:
Telem: 918600623
GTalk: pedrotainha@gmail.com

:: ANTES DE IMPRIMIR, PENSE NO AMBIENTE::

**Comment by RehanSaeed** [comment]
Cool, I'll close this for now. Reopen if it happens again.
