### ISSUE TITLE
RedirectToCanonicalUrlAttribute lowercase rule breaks password reset tokens

### ISSUE THREAD

**Issue by jums** [RehanSaeed/ASP.NET-MVC-Boilerplate#57]
RedirectToCanonicalUrlAttribute's lowercase rule should probably only force URL's path part to be lowercase. QueryString often contains case-sensitive data as is the case with ASP.NET 5 Identity's password reset and email confirmation links with the security tokens which are case-sensitive. Using the lowercase rule breaks the token authorization since the token is altered.

Maybe this part should be deleted, or give more control over the rule:
https://github.com/RehanSaeed/ASP.NET-MVC-Boilerplate/blob/master/Source/MVC6/Boilerplate.Web.Mvc6/Filters/RedirectToCanonicalUrlAttribute.cs#L151-L162

**Comment by RehanSaeed** [comment]
If you allow lower/upper case differences in the query string of a URL, then those are different URL's according to search engines. That said, there are times when you want to allow upper case query string parameters so:

I added a new `[NoLowercaseQueryString]` last night which you can add to the account controller. This allows uppercase characters in the query string. You can update to the latest Boilerplate.Web.Mvc6 NuGet package, I'll do the same for MVC 5 soon.

Please give this a try and let me know if you have any issues.

**Comment by RehanSaeed** [comment]
I tested out ASP.NET Identity, using the new `[NoLowercaseQueryString]` attribute on the AccountController (Or just the actions where it is needed) does the trick. All released in the NuGet update.

**Comment by jums** [comment]
Seems like a good solution and works for me, thanks.

**Comment by HugCoder** [comment]
Had trouble getting forgot password functionality working, but after debugging I noticed that the whole code was in lower case and I remembered that there was a setting for converting all URLs to lower case. Adding the `[NoLowercaseQueryString]` attribute to the ResetPassword view solved this, thanks for implementing it!
