### ISSUE TITLE
Example of sites made on ASP.NET-MVC-Boilerplate: Are there?

### ISSUE THREAD

**Issue by biapar** [RehanSaeed/ASP.NET-MVC-Boilerplate#59]
Example of sites made on ASP.NET-MVC-Boilerplate: Are there?

**Comment by RehanSaeed** [comment]
When you create a new site using the template, it has a link to my blog. I recieve a large number of referrer links from new blogs on the internet and I've checked out quite a few to see what people are doing. There are 55,500 downloads of this template not including Git clones, it's hard to say how many sites that translates to but I would guess a few thousand maybe?

I will add a link on the main page and a TODO item in the ReadMe for the template itself. Thanks for the suggestion.
