### ISSUE TITLE
gulp-minify-css is deprecated.

### ISSUE THREAD

**Issue by ChrisOMetz** [RehanSaeed/ASP.NET-MVC-Boilerplate#67]
As stated on https://www.npmjs.com/package/gulp-minify-css this package is deprecated now.

> Deprecation warning
> 
> This package has been deprecated in favor of gulp-cssnano, which should offer more advanced optimizations.

Therefore gulp-cssnano should be the "carefully choosen" default. 
... that's why I love the open source world...

**Comment by RehanSaeed** [comment]
Thanks for the notice Chris. So many packagesbeing used, it's hard to keep up. I'll make the switch in the next update.

**Comment by RehanSaeed** [comment]
Fixed in the next release.
