### ISSUE TITLE
Enable HTTPS in development environment by building a version of RequireHttpsAttribute which supports port numbers.

### ISSUE THREAD

**Issue by cottsak** [RehanSaeed/ASP.NET-MVC-Boilerplate#69]
Was looking at your [TODO List](https://github.com/RehanSaeed/ASP.NET-MVC-Boilerplate/blob/master/TODO.md) and thought I could help with the `Enable HTTPS in development environment by building a version of RequireHttpsAttribute which supports port numbers.`

https://github.com/cottsak/DevCookie/blob/master/DevCookie.Web/App_Start/RedirectToHttpsHelper.cs supports port numbers, port numbers in config as well as load balancer headers (like nginx/appharbor environments).

**Comment by RehanSaeed** [comment]
My original plan was to implement this for MVC 6 so it could be used in the development environment where you are most likely using a port number like `localhost:5000` to get to your site. In Staging or Production, the standard RequireHttpsAttribute could be used which does not support port numbers.

I hadn't really planned to implement this for MVC 5 as in your link but it would certainly help. That implementation using [X-Forwarded-Proto](https://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/x-forwarded-headers.html) is certainly interesting and not something I was aware of. I've mostly used Azure. Is this a standard setup in an AWS load balanced environment? I'm trying to get a feel for how often people come across this HTTP header and need to make use of it.

**Comment by cottsak** [comment]
@RehanSaeed It's a thing in Nginx which includes AppHarbor and prob Mono deployments depending on the server. The F5 load balancer may also do this as I've seen it before on other on-premises hosting environments where load balancers strip SSL.

**Comment by RehanSaeed** [comment]
Most people will be using IIS and will not come across this then. I would not be averse to adding a filter to the Boilerplate NuGet package however so people can use it if they need to.

Quick question, since you are using Nginx with Boilerplate. I would like to add an option in the MVC 6 template for web server, so imagine a check box for IIS and for Nginx. Enabling the IIS check box gives you a pre-configured web.config file. Having no experience with Nginx, what would that check box do?

**Comment by cottsak** [comment]
Sorry but I'm not using this framework. I just stumbled upon your todo list somehow and thought I could, share some code that might be useful.

**Comment by RehanSaeed** [comment]
Really appreciate it @cottsak. I've updated the TODO list with 'Add an option to choose the web-server you are using IIS, Nginx etc.'.

**Comment by omidkrad** [comment]
Linking related AppHarbor [support item](https://support.appharbor.com/discussions/problems/401-requirehttps-attribute-doesnt-work-in-aspnet-mvc3-on-appharbor).
