### ISSUE TITLE
Enhancements Security 

### ISSUE THREAD

**Issue by smartmeter** [RehanSaeed/ASP.NET-MVC-Boilerplate#70]
Hi Have some suggestions for security and user management

- [ ] - Can you include a view for user management, _and if possible multitenancy_
- [ ] - Can you include honey pot to track the list of scammy sites reported ( a good list reported by the government directly) [1](http://j.mp/1R97nz9)  [2](http://j.mp/1STzo1a)
- [ ] - In the bundle config you have fall back options, can you also please extend this to support IE 8 shiv, I can include the code

``

- [ ]  notification to both 1) target users and/or 2) pub sub would be nice too like Hangfire.io with Toastr

**Comment by RehanSaeed** [comment]
Boilerplate does not contain any authentication at the moment let alone user management. Take a look at Azure Active Directory or IdentityServer4, it has user management covered.

Spam prevention is interesting. The two links you provided are both in PHP. I don't think this is a feature that every site needs however.

I deliberately removed support for IE8. Support for IE8 is being dropped by a lot of sites these days as it is a pain to code for. Only [1%](http://caniuse.com/usage-table) of browsers use it IE8 and most of those are corporations who ban the use of Chrome or Firefox for their users. The next version of Bootstrap will drop support for it altogether. You can add respond.js if you need to support it for work.

Notifications are cool but not something every site needs. Boilerplate is supposed to contain everything that *every* site needs to be fast, effecient, secure, accessible etc.

**Comment by smartmeter** [comment]
ok thx :+1:
