### ISSUE TITLE
templates new project - Routes cannot find home or contact 

### ISSUE THREAD

**Issue by patagoniahiker** [RehanSaeed/ASP.NET-MVC-Boilerplate#71]
Hi, nice template, I can see a lot of love went into it, love it!

I created a new project after updating my extensions as per check list, and using your template, but my app no longer fires up. Worked with an older early last yr 1.07 or something, just overwrote all that... and its broken now.

Btw, your comments and explanation are what made it easier than using the Nweb Sec!!! :+1: 

I followed the Pre-Requisites

-     Update Visual Studio - Update your version of Visual Studio with all patches and updates.
-     Update NuGet - Update the NuGet Visual Studio extension from the Tools -> Extensions and Updates menu.
-     Install Web Essentials - Install the Web Essentials Visual Studio extension. This is required to compile LESS code to CSS as well as giving you an awesome web development experience

**Its broken and I am getting errors on basic routes, can you please help**

### The resource cannot be found.

Description: HTTP 404. The resource you are looking for (or one of its dependencies) could have been removed, had its name changed, or is temporarily unavailable.  Please review the following URL and make sure that it is spelled correctly. 

Requested URL: /Home/Contact _even for Index_

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.6.1038.0

1. Why does bundling with fallback fail, what do I need to do custom here? I was not able to follow this.
2. Can I turn off autofac?
3. Whats going on with the routes, the default routes should be able to find the actions like home? How can I switch back to default routes and get rid of attribute routing, will this impact security
4. Are you planning on adding recaptca?
5. How to use the home controller routes, I am new to this - sorry..
6. There are 2 startup classes, what are they doing besides the default MVC way?

.thanks
patty

**Comment by patagoniahiker** [comment]
I turned off the routing attributes and that did not help...

## A route named 'HomeGetIndex' could not be found in the route collection.
Parameter name: name

**Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. **

Exception Details: System.ArgumentException: A route named 'HomeGetIndex' could not be found in the route collection.
Parameter name: name

Source Error: 


Line 29: <header class="jumbotron">
Line 30:     <h1>@ViewBag.Title</h1>
Line 31:     <p class="lead">@ViewBag.Description</p>
Line 32:     <p><a href="https://github.com/RehanSaeed/ASP.NET-MVC-Boilerplate" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
Line 33: </header>

**Comment by smartmeter** [comment]
Did not work for me either, I think its broken.

**Comment by RehanSaeed** [comment]
`/Home/Contact` is not a valid URL. The Contact page can be found at `/contact`.

Visual Studio has this silly feature which opens a page for you based on the view you are looking at when you start debugging. It's just a time saving feature. It creates URL's for debugging in the form `ControllerName/ViewName` but the HomeController is different. It does not make sense to have a URL like `Home/Contact` when you can just have `/contact`.

If you want to turn this off, go to:

1. Project Properties
2. Web Tab
3. Start Action
4. Select specific page and enter `/`
