### ISSUE TITLE
Project file .csproj template typo

### ISSUE THREAD

**Issue by JesterDollar** [RehanSaeed/ASP.NET-MVC-Boilerplate#76]
Small typo, big problem - can't reach any packages when compiling.  The latest version ( I went from v2.9.1 to v 2.9.7 ) has a missing "." in the packages path in .csproj file: ".\packages" and not "..\packages", therefore tons of errors when compiling.

Using MVC5 version of template - just create new project from template and try to build, NOTHING else, no changes, etc.

For anyone with this problem the quick fix is just a search and replace in the .csproj file - since this only happens during project creation.

**Comment by RehanSaeed** [comment]
Thanks for reporting. Boilerplate runs a bit of code which adjusts the NuGet packages path depending on where you create your project in relation to your solution file or if you have some custom settings in a NuGet.config file.

Can you please post your folder hierarchy, telling me how many folders down your project was, in relation to your solution. I can then try recreating the problem.

**Comment by JesterDollar** [comment]
Yeah, I was just looking at the TemplateBuilder part but nothing stuck out - however, I just had a quick thought and verified it:  Create a new project called "MyProj.site" **BUT **name the solution "MyProj" and it occurs - works fine if the project name matches the solution name.  I often name my web parts .site cause I add other projects to the solution like .azure, .database, etc.

**Comment by RehanSaeed** [comment]
Looks like it occurs when there is a `.` in the name. I'll investigate.

**Comment by RehanSaeed** [comment]
I've submitted a PR containing a fix to the TemplateBuilder project. When it is published in a NuGet package, I'll add it to ASP.NET MVC Boilerplate.

**Comment by JesterDollar** [comment]
Cool.  Thanks.

**Comment by larry609** [comment]
I'm going to try your system out; while I like the thought of a good
boilerplate system, the fact that you are so responsive to users' problems
is, by far, the biggest reason I'm going to try it.

Larry Wilson
"qui nos opprimere velint, illos libenter devoramus"

**Comment by RehanSaeed** [comment]
@larry609 This project is alive, while I am fit, healthy and bored enough to run it. Feel free to take some benefit from it.

**Comment by larry609** [comment]
Do you have a suggestion about the best utility to integrate VS 2012 and
GitHub?

Thanks.

Larry Wilson
"qui nos opprimere velint, illos libenter devoramus"

**Comment by RehanSaeed** [comment]
@larry609 

[Visual Studio Tools for Git](https://visualstudiogallery.msdn.microsoft.com/abafc7d6-dcaa-40f4-8a5e-d6724bdb980c) and [GitHub Desktop](https://desktop.github.com/).

Use the Posh Git command line that comes with GitHub Desktop to really learn Git. I think learning the command line is important as you can't do everything from visual studio.

**Comment by RehanSaeed** [comment]
Fix released.
