### ISSUE TITLE
MVC 6 rewrite errors instead of redirect

### ISSUE THREAD

**Issue by jhermsen** [RehanSaeed/ASP.NET-MVC-Boilerplate#83]
Hi I have a little issue.
I though the error pages would rewrite instead of redirect, but when I get a 404 error I get redirected to /error/404.
I think google search craweler might have an issue with this as it is seeying a page as permanently moved instead of not available.

**Comment by RehanSaeed** [comment]
Are you using Azure? [this](https://github.com/RehanSaeed/ASP.NET-MVC-Boilerplate/issues/82) issue may be related.

**Comment by RehanSaeed** [comment]
The `httpErrors` section has `PassThrough` set for `existingResponse` in Debug mode (which causes a redirect but is required for some debug functionality like Glimpse to work) but when you publish (Not build) in Release mode it sets the value to `Replace` instead (See Web.Release.config).

**Comment by RehanSaeed** [comment]
Merging your fix.
