### ISSUE TITLE
MVC5 404 not found + solution

### ISSUE THREAD

**Issue by Binnette** [RehanSaeed/ASP.NET-MVC-Boilerplate#84]
Hello,

I encounter some 404 errors, when starting my apllication.
The cause is Visual Studio open url http://localhost:6619/Home/Customroute
But this url is inccorect. The correct url is http://localhost:6619/customroute

Here is the way to fix it :
1. Open Project properties
2. Go to Web Tab
3. Check "Specific Page" for Start Action
4. Leave "Specific Page" blank

In fact, this will open http://localhost:6619/ in web browser instead of the "Current Page" (this one give wrong url).

So can you add thoses steps in your Readme file please ?

**Comment by RehanSaeed** [comment]
I've just made this the default. Thanks for the suggestion. Expect to see it in the next release.

**Comment by Binnette** [comment]
Thanks a lot for this VERY usefull boilerplate. :+1:
