### ISSUE TITLE
MVC 6 Error Controller causing Bad GateAway on IIS

### ISSUE THREAD

**Issue by abuson** [RehanSaeed/ASP.NET-MVC-Boilerplate#86]
After calling url with status code below 200 (localhost/error/1/) IIS returns BadGateway ugly page.
For Greater or Equal 200 it returns nice error page from MVC. 
It can be easly fixed by changing route and translate anything below 200 to 404 Not Found .

**Comment by RehanSaeed** [comment]
Thanks for the fixes. I've added you as a contributer on the home page.
