### ISSUE TITLE
Port 8080 Conflict with TFS Express

### ISSUE THREAD

**Issue by rccnw** [RehanSaeed/ASP.NET-MVC-Boilerplate#9]
It appears the default port 8080 is already in use by TFS Express.
Removing TFS express resolved the issue. 
Everything ok now and I can create new projects from the template.
Although the port can be modified after creating the project, I was blocked from creating a new project until I resolved the conflict.

This is the error that occurred when creating new project from template (after installing extension).

"The site for the URL 'http://localhost:8080/', configured for Web project <MyProject> exists on both the local IIS web server and the IIS Express web server. You need to use IIS Manager to change this site's binding(s) in IIS"

**Comment by RehanSaeed** [comment]
Thanks for letting me know, once again. I Modified the .csproj file so that the IISUrl element is empty. This allows a random port to be chosen each time a project is generated from the template. Will check in code and update the template this evening.
