### ISSUE TITLE
VisualStudio 2015 Update 2 compatible

### ISSUE THREAD

**Issue by kdaveid** [RehanSaeed/ASP.NET-MVC-Boilerplate#91]
Running the MVC6 wizard and webpage with VS 2015 **Update 2**. Just for people to know the requirements in [How to build](https://github.com/RehanSaeed/ASP.NET-MVC-Boilerplate/blob/master/HOW%20TO%20BUILD.md#how-to-build).

**Comment by RehanSaeed** [comment]
Yes, I think you only need VS 2015 or above. I'm currently using Update 2. I've updated the How to Build document.
