### ISSUE TITLE
redirect to https

### ISSUE THREAD

**Issue by fisenkodv** [RehanSaeed/ASP.NET-MVC-Boilerplate#93]
Page is redirected to **https**://localhost:5000 when launch _dnx web_.

**Comment by RehanSaeed** [comment]
I guess you are doing this from the command line and not from visual studio. When using the command line, you need to pass the server url yourself. If you specify this URL in project.json, then IIS Express stops working :( Maybe RC2 will fix this problem.

**Comment by RehanSaeed** [comment]
Feel free to reopen this issue if you have any more questions.
