### ISSUE TITLE
Suggestion: Include prefix.io

### ISSUE THREAD

**Issue by dotnetshadow** [RehanSaeed/ASP.NET-MVC-Boilerplate#94]
What are your thoughts on including:
http://www.prefix.io/

**Comment by RehanSaeed** [comment]
It's a very cool project. I've heard of it but not tried it. Have you? How does it compare with Glimpse? This could be added as an option to choose Glimpse or Prefix.io.

It looks like you have to install an MSI, install a NuGet package and add some middleware to get it working. Not sure how I would get users to install prefix.io.

**Comment by dotnetshadow** [comment]
You can check for pros and cons for glimpse vs prefix
http://support.stackify.com/hc/en-us/articles/207800393-Prefix-vs-Glimpse-for-ASP-NET

ASP.NET Core 
http://support.stackify.com/hc/en-us/articles/209962473-Using-Prefix-with-ASP-NET-Core

I was thinking more having the option to include:
`app.UseMiddleware<StackifyMiddleware.RequestTracerMiddleware>();`

Obviously people could just manually add this into the template, just thought it could be beneficial because it runs in development mode on your own computer as opposed to a service like application insights.

**Comment by RehanSaeed** [comment]
Sounds good to me. We'll add this as a choice between Glimpse and Prefix.io and put in a comment above your line of code explaining where to install prefix.io. Maybe even add an entry into the ReadMe.html file. Am willing to accept a PR for this work, would be very similar to the Glimpse optional feature.

**Comment by RehanSaeed** [comment]
Updated the TODO with this feature. Will get around to it eventually.

https://github.com/RehanSaeed/ASP.NET-MVC-Boilerplate/blob/master/TODO.md
