### ISSUE TITLE
CSS/SCSS gulp lint

### ISSUE THREAD

**Issue by Huntk23** [RehanSaeed/ASP.NET-MVC-Boilerplate#99]
Hi @RehanSaeed,

Question about the `lint-css` task in the gulpfile:
I added the gulp-debug module to the pipe to see if it was picking up files under the source of `Styles/**/*.{scss}` and the debug() option is showing 0 items. I placed in the site.scss under Styles/ bogus scss that should have thrown a warning/error and it didn't.

Any insight on this?

**Comment by RehanSaeed** [comment]
It was not highlighted but you needed ruby installed to get that working. I've just found a new recently released gulp task which does not have this requirement. The commit below switches to the new task and ensures that it works:

https://github.com/RehanSaeed/ASP.NET-MVC-Boilerplate/commit/93909d083b68a5fdbf51bf685f9bc6ad4a535f48

Note that I am working on getting an RC2 release out. This will be included.
